
USE KFCDB
GO

--Task 2.6 DB shrink and backup creation

ALTER INDEX ALL ON Supply REBUILD

go
ALTER INDEX ALL ON Customer REBUILD

go
ALTER INDEX ALL ON Supplier REBUILD

go
ALTER INDEX ALL ON [Transaction] REBUILD

go
ALTER INDEX ALL ON SupplierContactPerson REBUILD

go
ALTER INDEX ALL ON Restaurant REBUILD

go
ALTER INDEX ALL ON Product REBUILD

go
ALTER INDEX ALL ON Position REBUILD

go
ALTER INDEX ALL ON PaymentMethod REBUILD

go
ALTER INDEX ALL ON OrderDetail REBUILD

go
ALTER INDEX ALL ON Employee REBUILD

go
ALTER INDEX ALL ON [Order] REBUILD

go
ALTER INDEX ALL ON Ingredient REBUILD

go
ALTER INDEX ALL ON FoodCategory REBUILD

go
ALTER INDEX ALL ON Feedback REBUILD

go
ALTER INDEX ALL ON EmployeeSchedule REBUILD

go
DBCC SHRINKDATABASE(KFCDB)

go
BACKUP DATABASE KFCDB TO DISK = 'D:\KFCDB.bak' 

